# Generated by Django 6.0.4 on 2026-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_city_remove_bloodrequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
