# Generated by Django 5.2.6 on 2026-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bloodrequest_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='sender_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
