# Generated by Django 5.2.6 on 2026-05-31 08:29

from django.db import migrations, models


def populate_blood_groups_and_cities(apps, schema_editor):
    BloodGroup = apps.get_model('myapp', 'BloodGroup')
    groups = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-']
    for g in groups:
        BloodGroup.objects.get_or_create(name=g)

    City = apps.get_model('myapp', 'City')
    default_cities = [
        'Lahore', 'Karachi', 'Islamabad', 'Faisalabad', 'Multan', 'Peshawar', 'Bahawalpur', 'Sialkot', 
        'Gujranwala', 'Quetta', 'Sargodha', 'Sukkur', 'Jhang', 'Sheikhupura', 'Rahim Yar Khan', 'Gujrat', 
        'Mardan', 'Kasur', 'Sahiwal', 'Okara', 'Wah Cantonment', 'Dera Ghazi Khan'
    ]
    for name in default_cities:
        City.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bloodrequest_sender_acknowledged'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Blood Group',
                'verbose_name_plural': 'Blood Groups',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(populate_blood_groups_and_cities),
    ]
